// insurance/RestrictedTerms.js

export const restrictedTerms = [
  // Core terms
  "medicaid",
  "medicare",
  "blue cross community",
  "meridian",
  "aetna better health",
  "chip",
  "children's health insurance program",
  "illinois all kids",
  "dentaquest",
  "molina healthcare",
  "blue cross blue shield",
  "illinois medicaid",
  "medicaid of illinois",
  "medicare advantage",
  "medicaid advantage",

  // Variations and misspellings
  "medicaide",
  "medcaid",
  "blue cross community",
  "children's health",
  "children's program",
  "health insurance program",
  "illinois kids",
  "illinois all kids program",
  "denta quest",
  "molina",
  "molina health",
  "med",
  "aid",
  "care",
  "crossover",
  "chip",
  "children",
  "health",
  "kids",

  "advantage",

  // No insurance terms
  "no insurance",
  "none",
  "n/a",
  "na",
  "no",
  "not insured",
  "self pay",
  "self-pay",
  "out of pocket",
  "out-of-pocket",
  "cash",
  "",
  "unknown",
  "unsure",
  "not sure",
  "selfpay",
  "selfpayment",
  "self-payment",
  "outofpocket",
  "outofpocketpayment",
];
